# SEO Values
title: No Mans Sky Social Emojis
url: https://emoji.nomanssky.social
icon: favicon.ico

# GitHub Values
github:
  owner_name: AssistantApps
  owner_url: https://github.com/AssistantApps
  repository_url: https://github.com/AssistantApps/NoMansSky.Social.Emojis

show_downloads: false
show_header: false
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
